name: Only Tests

on:
  push:
    branches-ignore:
      - main
      - master

jobs:
  run-all-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'maven'

      - name: All the Tests and Coverage Checks
        run: mvn clean install
